[font]
normal = { family = "Terminess Nerd Font Mono" }
size = 9

[colors.primary]
foreground = "#c0caf5"
background = "#1a1b26"

[colors.normal]
black = "#1D202F"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"


[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

[keyboard]
bindings = [
    { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
    { key = "-", mods = "Control", action = "DecreaseFontSize" },
    { key = "L", mods = "Control|Shift", action = "ClearHistory" },
]
